language: python

python:
  - "3.6"

# command to install dependencies
install: 
  - pip3 install -q -r requirements.txt
  - pip3 install -q -r source/_scripts/_python/requirements.txt

# command to run tests
script: 
  - make py
  - make htmlall

before_deploy:
  - make linkcheck
  # compress current build of Simplified Chinese in case of tagged build
  - tar -zcvf clearlinux-docs-zh-CN.tar.gz -C source/_build/html/zh_CN .
  # only deploy the latest tagged release of Simplified Chinese docs
  - wget https://github.com/clearlinux/clear-linux-documentation/releases/latest/download/clearlinux-docs-zh-CN.tar.gz
  - mkdir source/_build/html/zh_CN
  - tar xvzf clearlinux-docs-zh-CN.tar.gz -C source/_build/html/zh_CN

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target-branch: latestHTML
    on:
      branch: master
    local_dir: source/_build/html/
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target-branch: developmentHTML
    on:
      branch: development
    local_dir: source/_build/html/
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: clearlinux-docs-zh-CN.tar.gz
    on:
      tags: true


after_deploy:
  - wget $PUBLISH_URL
  - cat clearlinux-latest